language: node_js

node_js:
  - 10
  - 12

cache: yarn

script:
  - yarn test
  - npx codecov

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: 12
      script:
        - yarn build
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          tags: true
