version: 2

jobs:
  ci:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install packages
          command: yarn
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
      - run:
          name: Run tests and upload to Codecov
          command: |
            yarn test
            npx codecov
      - store_test_results:
          path: test/unit
      - run:
          name: Build the project
          command: |
            yarn build

  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  tagged-build:
    jobs:
      - ci
      - publish:
          requires:
            - ci
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/